Use RLIMIT_DATA when RLIMIT_AS doesn't exist.
Fixes:

    recidivm.c: In function 'child':
    recidivm.c:79: error: 'RLIMIT_AS' undeclared (first use in this function)

on OpenBSD.